### ISSUE TITLE
TODO entrega final

### ISSUE THREAD

**Issue by J-888** [J-888/DVI-Kelricks-odyssey#1]
Pantallas:
- [x] creditos
- [x] controles (opcional)

Items: 
- [x] Bow (pendiente fix flecha a la izda)
- [x] Staf
- [ ] Boomerang (opcional)
- [x] Temporizadores para items

Trabajo pendiente en general:
- [x] Mas enemigos
- [ ] Mejor / mas IAs (disparar el jugador prediciendo su mov, evitar obstaculos)
- [x] Inmunidades de enemigos
- [x] Cueva procedural
- [x] Boss y lvl
- [ ] Sonidos
- [ ] Musica

Memoria (readme.md):
- [ ] Diseño del juego <- doc anterior ampliado (se puede confeccionar a partir del documento de concepto entregado anteriormente, ampliando con las nuevas mecánicas añadidas y explicando mínimamente en qué consisten. 1. Objetivo del juego: cómo se gana, cómo se pierde. 2. Principales mecánicas)
- [ ] Diseño de la implementación (qué tecnología se ha usado (Quintus u otro
motor), arquitectura y principales componentes)
- [ ] Equipo de trabajo y reparto de tareas: descripción del trabajo realizado
por cada uno de los integrantes del grupo y carga de trabajo realizada
(0%-100%)
- [ ] Fuentes y referencias: Referencias a todos los assets no propios utilizados en
la realización del juego. Si se han seguido tutoriales o juegos ya realizados,
detallar cuáles son las partes específicas que han sido implementadas por
los estudiantes durante la realización de este proyecto.
